// Generated by scripts/generate-miniprogram-icons.mjs. Do not edit manually.
export const ICON_TONES = ["ink","surface","primary","danger"] as const;
export type UiIconTone = typeof ICON_TONES[number];
export const ICON_PATHS = {
  "home": {
    ink: "/assets/icons/home.svg",
    surface: "/assets/icons/home-surface.svg",
    primary: "/assets/icons/home-primary.svg",
    danger: "/assets/icons/home-danger.svg",
  },
  "wardrobe": {
    ink: "/assets/icons/wardrobe.svg",
    surface: "/assets/icons/wardrobe-surface.svg",
    primary: "/assets/icons/wardrobe-primary.svg",
    danger: "/assets/icons/wardrobe-danger.svg",
  },
  "camera": {
    ink: "/assets/icons/camera.svg",
    surface: "/assets/icons/camera-surface.svg",
    primary: "/assets/icons/camera-primary.svg",
    danger: "/assets/icons/camera-danger.svg",
  },
  "camera-plus": {
    ink: "/assets/icons/camera-plus.svg",
    surface: "/assets/icons/camera-plus-surface.svg",
    primary: "/assets/icons/camera-plus-primary.svg",
    danger: "/assets/icons/camera-plus-danger.svg",
  },
  "image": {
    ink: "/assets/icons/image.svg",
    surface: "/assets/icons/image-surface.svg",
    primary: "/assets/icons/image-primary.svg",
    danger: "/assets/icons/image-danger.svg",
  },
  "scissors": {
    ink: "/assets/icons/scissors.svg",
    surface: "/assets/icons/scissors-surface.svg",
    primary: "/assets/icons/scissors-primary.svg",
    danger: "/assets/icons/scissors-danger.svg",
  },
  "trash": {
    ink: "/assets/icons/trash.svg",
    surface: "/assets/icons/trash-surface.svg",
    primary: "/assets/icons/trash-primary.svg",
    danger: "/assets/icons/trash-danger.svg",
  },
  "rotate-left": {
    ink: "/assets/icons/rotate-left.svg",
    surface: "/assets/icons/rotate-left-surface.svg",
    primary: "/assets/icons/rotate-left-primary.svg",
    danger: "/assets/icons/rotate-left-danger.svg",
  },
  "rotate-right": {
    ink: "/assets/icons/rotate-right.svg",
    surface: "/assets/icons/rotate-right-surface.svg",
    primary: "/assets/icons/rotate-right-primary.svg",
    danger: "/assets/icons/rotate-right-danger.svg",
  },
  "reset": {
    ink: "/assets/icons/reset.svg",
    surface: "/assets/icons/reset-surface.svg",
    primary: "/assets/icons/reset-primary.svg",
    danger: "/assets/icons/reset-danger.svg",
  },
  "layers": {
    ink: "/assets/icons/layers.svg",
    surface: "/assets/icons/layers-surface.svg",
    primary: "/assets/icons/layers-primary.svg",
    danger: "/assets/icons/layers-danger.svg",
  },
  "sparkles": {
    ink: "/assets/icons/sparkles.svg",
    surface: "/assets/icons/sparkles-surface.svg",
    primary: "/assets/icons/sparkles-primary.svg",
    danger: "/assets/icons/sparkles-danger.svg",
  },
  "shopping-bag": {
    ink: "/assets/icons/shopping-bag.svg",
    surface: "/assets/icons/shopping-bag-surface.svg",
    primary: "/assets/icons/shopping-bag-primary.svg",
    danger: "/assets/icons/shopping-bag-danger.svg",
  },
  "user": {
    ink: "/assets/icons/user.svg",
    surface: "/assets/icons/user-surface.svg",
    primary: "/assets/icons/user-primary.svg",
    danger: "/assets/icons/user-danger.svg",
  },
  "settings": {
    ink: "/assets/icons/settings.svg",
    surface: "/assets/icons/settings-surface.svg",
    primary: "/assets/icons/settings-primary.svg",
    danger: "/assets/icons/settings-danger.svg",
  },
  "chevron-right": {
    ink: "/assets/icons/chevron-right.svg",
    surface: "/assets/icons/chevron-right-surface.svg",
    primary: "/assets/icons/chevron-right-primary.svg",
    danger: "/assets/icons/chevron-right-danger.svg",
  },
  "chevron-left": {
    ink: "/assets/icons/chevron-left.svg",
    surface: "/assets/icons/chevron-left-surface.svg",
    primary: "/assets/icons/chevron-left-primary.svg",
    danger: "/assets/icons/chevron-left-danger.svg",
  },
  "chevron-down": {
    ink: "/assets/icons/chevron-down.svg",
    surface: "/assets/icons/chevron-down-surface.svg",
    primary: "/assets/icons/chevron-down-primary.svg",
    danger: "/assets/icons/chevron-down-danger.svg",
  },
  "search": {
    ink: "/assets/icons/search.svg",
    surface: "/assets/icons/search-surface.svg",
    primary: "/assets/icons/search-primary.svg",
    danger: "/assets/icons/search-danger.svg",
  },
  "bar-chart-3": {
    ink: "/assets/icons/bar-chart-3.svg",
    surface: "/assets/icons/bar-chart-3-surface.svg",
    primary: "/assets/icons/bar-chart-3-primary.svg",
    danger: "/assets/icons/bar-chart-3-danger.svg",
  },
  "wand-sparkles": {
    ink: "/assets/icons/wand-sparkles.svg",
    surface: "/assets/icons/wand-sparkles-surface.svg",
    primary: "/assets/icons/wand-sparkles-primary.svg",
    danger: "/assets/icons/wand-sparkles-danger.svg",
  },
  "plus": {
    ink: "/assets/icons/plus.svg",
    surface: "/assets/icons/plus-surface.svg",
    primary: "/assets/icons/plus-primary.svg",
    danger: "/assets/icons/plus-danger.svg",
  },
  "x": {
    ink: "/assets/icons/x.svg",
    surface: "/assets/icons/x-surface.svg",
    primary: "/assets/icons/x-primary.svg",
    danger: "/assets/icons/x-danger.svg",
  },
  "check": {
    ink: "/assets/icons/check.svg",
    surface: "/assets/icons/check-surface.svg",
    primary: "/assets/icons/check-primary.svg",
    danger: "/assets/icons/check-danger.svg",
  },
  "loader": {
    ink: "/assets/icons/loader.svg",
    surface: "/assets/icons/loader-surface.svg",
    primary: "/assets/icons/loader-primary.svg",
    danger: "/assets/icons/loader-danger.svg",
  },
} as const;
export type UiIconName = keyof typeof ICON_PATHS;
