export const ICON_PATHS = {
  home: "/assets/icons/home.svg",
  wardrobe: "/assets/icons/wardrobe.svg",
  camera: "/assets/icons/camera.svg",
  "camera-plus": "/assets/icons/camera.svg",
  image: "/assets/icons/image.svg",
  scissors: "/assets/icons/scissors.svg",
  trash: "/assets/icons/trash.svg",
  "rotate-left": "/assets/icons/rotate-left.svg",
  "rotate-right": "/assets/icons/rotate-right.svg",
  reset: "/assets/icons/reset.svg",
  layers: "/assets/icons/layers.svg",
  sparkles: "/assets/icons/sparkles.svg",
  "shopping-bag": "/assets/icons/shopping-bag.svg",
  user: "/assets/icons/user.svg",
  settings: "/assets/icons/settings.svg",
  "chevron-right": "/assets/icons/chevron-right.svg",
  "chevron-left": "/assets/icons/chevron-left.svg",
  "chevron-down": "/assets/icons/chevron-down.svg",
  search: "/assets/icons/search.svg",
  "bar-chart-3": "/assets/icons/bar-chart-3.svg",
  "wand-sparkles": "/assets/icons/wand-sparkles.svg",
  plus: "/assets/icons/plus.svg",
  x: "/assets/icons/x.svg",
  check: "/assets/icons/check.svg",
  loader: "/assets/icons/loader.svg",
} as const;

export type UiIconName = keyof typeof ICON_PATHS;

export const ICON_GLYPHS: Record<UiIconName, string> = {
  home: "⌂",
  wardrobe: "▣",
  camera: "□",
  "camera-plus": "+",
  layers: "▤",
  sparkles: "✦",
  "shopping-bag": "▢",
  user: "○",
  settings: "⚙",
  "chevron-right": ">",
  "chevron-left": "<",
  "chevron-down": "⌄",
  search: "⌕",
  "bar-chart-3": "▥",
  "wand-sparkles": "✦",
  plus: "+",
  x: "×",
  check: "✓",
  loader: "○",
  image: "▧",
  scissors: "✂",
  trash: "⌫",
  "rotate-left": "↶",
  "rotate-right": "↷",
  reset: "⟳",
};
