export const ICON_PATHS = {
  home: "/assets/icons/home.png",
  wardrobe: "/assets/icons/wardrobe.png",
  camera: "/assets/icons/camera.png",
  "camera-plus": "/assets/icons/camera-plus.png",
  layers: "/assets/icons/layers.png",
  sparkles: "/assets/icons/sparkles.png",
  "shopping-bag": "/assets/icons/shopping-bag.png",
  user: "/assets/icons/user.png",
  settings: "/assets/icons/settings.png",
  "chevron-right": "/assets/icons/chevron-right.png",
  "chevron-left": "/assets/icons/chevron-left.png",
  "chevron-down": "/assets/icons/chevron-down.png",
  search: "/assets/icons/search.png",
  "bar-chart-3": "/assets/icons/bar-chart-3.png",
  "wand-sparkles": "/assets/icons/wand-sparkles.png",
  plus: "/assets/icons/plus.png",
  x: "/assets/icons/x.png",
  check: "/assets/icons/check.png",
  loader: "/assets/icons/loader.png",
} as const;

export type UiIconName = keyof typeof ICON_PATHS;

export const ICON_GLYPHS: Record<UiIconName, string> = {
  home: "⌂",
  wardrobe: "▣",
  camera: "□",
  "camera-plus": "+",
  layers: "▤",
  sparkles: "✦",
  "shopping-bag": "▢",
  user: "○",
  settings: "⚙",
  "chevron-right": ">",
  "chevron-left": "<",
  "chevron-down": "⌄",
  search: "⌕",
  "bar-chart-3": "▥",
  "wand-sparkles": "✦",
  plus: "+",
  x: "×",
  check: "✓",
  loader: "○",
};
