import { TestEntry } from '../test-types';

export const e2eTests: TestEntry[] = [
  { testId: 'e2e:android-smoke', layer: 'e2e', filePath: 'scripts/android-e2e/run-android-e2e.ts --suite smoke', description: 'Real APK smoke flow via WebView CDP', tags: ['smoke'], blocking: true, executionPolicy: 'manual', executionNodes: [{ name: 'local-android' }], inputDescription: 'Installed APK, Android device, test API', expectedOutput: 'APK launches; auth, default closet, navigation and global create pass', expectedEvidence: 'Screenshots, logcat and API snapshots' },
  { testId: 'e2e:android-critical', layer: 'e2e', filePath: 'scripts/android-e2e/run-android-e2e.ts --suite critical', description: 'Real APK critical business flows via WebView CDP', tags: ['critical'], blocking: true, executionPolicy: 'manual', executionNodes: [{ name: 'local-android' }], inputDescription: 'Installed APK, Android device, test API', expectedOutput: 'Garment, wishlist, outfit, account isolation and force-stop restore flows pass', expectedEvidence: 'Screenshots, logcat and API snapshots' },
  { testId: 'e2e:android-full', layer: 'e2e', filePath: 'scripts/android-e2e/run-android-e2e.ts --suite full', description: 'Real APK smoke, critical and full-depth business flows via WebView CDP', tags: ['full'], blocking: true, executionPolicy: 'manual', executionNodes: [{ name: 'local-android' }], inputDescription: 'Installed APK, Android device, test API with E2E fault injection token for retry cases', expectedOutput: 'Smoke, critical, image asset restore, wishlist image conversion, cascade delete, server fault retry, AI no-key fallback entry and native boundary cases pass', expectedEvidence: 'Screenshots, logcat, ADB portrait screenshot, AI/fault logs and API snapshots' },
  { testId: 'e2e:account-page', layer: 'e2e', filePath: 'e2e/specs/account-page.spec.ts', description: 'Account page', tags: ['full'], blocking: false },
  { testId: 'e2e:two-device', layer: 'e2e', filePath: 'e2e/specs/two-device-data-sync.spec.ts', description: 'Two device data sync', tags: ['full'], blocking: false },
  { testId: 'e2e:cascade-delete', layer: 'e2e', filePath: 'e2e/specs/cascade-delete-sync.spec.ts', description: 'Cascade delete sync', tags: ['full'], blocking: false },
  { testId: 'e2e:online-failure-retry', layer: 'e2e', filePath: 'e2e/specs/online-failure-retry.spec.ts', description: 'Online failure retry', tags: ['full'], blocking: false },
  { testId: 'e2e:ai-recognition-failure', layer: 'e2e', filePath: 'e2e/specs/ai-recognition-failure-retry.spec.ts', description: 'AI recognition failure retry', tags: ['full'], blocking: false },
  { testId: 'e2e:dev-server-image', layer: 'e2e', filePath: 'e2e/specs/dev-server-image-verification.spec.ts', description: 'Dev server image verification', tags: ['full'], blocking: false },
  { testId: 'e2e:ai-live', layer: 'e2e', filePath: 'scripts/android-e2e/run-android-e2e.ts --suite ai-live', description: 'Real APK runner live MiniMax recognition with a real fixture image (manual)', tags: ['ai-live'], blocking: false, executionPolicy: 'manual', executionNodes: [{ name: 'local-android' }], inputDescription: 'Installed APK, Android device, test API, ALLOW_LIVE_AI_TEST=true, E2E_AI_MODE=live, ANDROID_E2E_AI_LIVE=1 and MINIMAX_API_KEY', expectedOutput: 'Backend MiniMax proxy returns candidate names and category for the real image fixture', expectedEvidence: 'ai-live-minimax-response.json and runner summary' },
];
