import { fetchGarments, fetchOutfits, fetchWishlist, type MiniGarment, type MiniOutfit, type MiniWishlistItem } from "../../../services/workspace";
import { getCapsuleGeometry } from "../../../utils/capsule-layout";

type Row = { id: string; name: string; subtitle: string; badge: string; value: string; imageUrl: string };

Page({
  data: { contentTopRpx: 0, loading: false, error: "", monthLabel: "", itemCount: 0, outfitCount: 0, monthlyOutfitCount: 0, monthlyOutfitEvents: 0, monthlyItemCount: 0, monthlyItemEvents: 0, idleCount: 0, recentRows: [] as Row[], idleRows: [] as Row[], purchaseRows: [] as Row[] },
  onLoad(this: any) { this.setData({ contentTopRpx: getCapsuleGeometry().contentTopRpx }); void this.load(); },
  async load(this: any) { this.setData({ loading: true, error: "" }); try { const [items, outfits, wishlist] = await Promise.all([fetchGarments(), fetchOutfits(), fetchWishlist()]); this.setData(buildStatistics(items, outfits, wishlist)); } catch (error) { this.setData({ loading: false, error: error instanceof Error ? error.message : "统计读取失败" }); } },
});

function buildStatistics(items: MiniGarment[], outfits: MiniOutfit[], wishlist: MiniWishlistItem[]) {
  const today = localDateKey(); const month = today.slice(0, 7); const itemFreq = items.map((item) => frequency(item.wornDates, month)); const outfitFreq = outfits.map((item) => frequency(item.wornDates, month));
  const recentRows: Row[] = [...items.map((item, index) => ({ id: item.id, name: item.name, subtitle: `${item.categoryLabel} · ${lastWornText(item.wornDates)}`, badge: "衣物", value: wearCountText(itemFreq[index]), imageUrl: item.imageUrl, score: score(itemFreq[index]) })), ...outfits.map((item, index) => ({ id: item.id, name: item.name, subtitle: `${item.itemCount} 件 · ${lastWornText(item.wornDates)}`, badge: "套装", value: wearCountText(outfitFreq[index]), imageUrl: item.imageUrl, score: score(outfitFreq[index]) }))].filter((row) => row.score > 0).sort((a,b)=>b.score-a.score).slice(0,6).map(({score: _score,...row})=>row);
  const idleRows = items.map((item) => { const last = item.wornDates[item.wornDates.length - 1]; const days = daysBetween(last || item.createdAt.slice(0,10), today); return { item, last, days }; }).filter((entry) => entry.item.status !== "archived" && entry.days >= 45).sort((a,b)=>b.days-a.days).slice(0,6).map(({item,last,days}) => ({ id:item.id,name:item.name,subtitle:`${item.categoryLabel} · ${last ? lastWornText([last]) : '从未记录'}`,badge:last?"闲置":"未穿",value:`${days} 天`,imageUrl:item.imageUrl }));
  const itemById = new Map(items.map((item)=>[item.id,item])); const purchaseRows = wishlist.flatMap((wish) => { const item = wish.convertedGarmentId ? itemById.get(wish.convertedGarmentId) : undefined; if (!item || !wish.convertedAt) return []; const date = wish.convertedAt.slice(0,10); const uses = item.wornDates.filter((worn)=>worn>=date).length; const days = Math.max(0,daysBetween(date,today)); const per30 = uses ? (uses / Math.max(1,days+1) * 30).toFixed(1) : "0"; return [{ id:wish.id,name:item.name,subtitle:`转入 ${date.replace(/-/g,'/')} · 每30天 ${per30} 次`,badge:uses?"已使用":"提醒",value:`买后 ${uses} 次`,imageUrl:item.imageUrl,zero:uses===0 }]; }).sort((a,b)=>Number(b.zero)-Number(a.zero)).slice(0,6).map(({zero:_zero,...row})=>row);
  return { loading:false,error:"",monthLabel:`${Number(month.slice(5))}月`,itemCount:items.length,outfitCount:outfits.length,monthlyOutfitCount:outfitFreq.filter((f)=>f.month>0).length,monthlyOutfitEvents:outfitFreq.reduce((sum,f)=>sum+f.month,0),monthlyItemCount:itemFreq.filter((f)=>f.month>0).length,monthlyItemEvents:itemFreq.reduce((sum,f)=>sum+f.month,0),idleCount:idleRows.length,recentRows,idleRows,purchaseRows };
}
function frequency(dates:string[],month:string){return{month:dates.filter((d)=>d.startsWith(month)).length,total:dates.length,last:dates[dates.length-1]||""}} function score(f:{month:number;total:number}){return f.month*100+f.total} function wearCountText(f:{month:number;total:number}){return f.month?`本月 ${f.month} 次`:`累计 ${f.total} 次`} function lastWornText(dates:string[]){const last=dates[dates.length-1];return last?`上次 ${last.replace(/-/g,'/')}`:"从未记录"} function localDateKey(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`} function daysBetween(a:string,b:string){return Math.max(0,Math.floor((Date.parse(`${b}T00:00:00Z`)-Date.parse(`${a}T00:00:00Z`))/86400000))}
