import fs from "node:fs";
const root = JSON.parse(fs.readFileSync("package.json", "utf8"));
const mini = JSON.parse(fs.readFileSync("apps/wechat-miniprogram/package.json", "utf8"));
const output = `// Generated by scripts/generate-miniprogram-build-info.ts. Do not edit manually.\nexport const APP_BUILD_VERSION = ${JSON.stringify(root.version)};\nexport const MINIPROGRAM_PACKAGE_VERSION = ${JSON.stringify(mini.version)};\n`;
const path = "apps/wechat-miniprogram/generated/build-info.ts";
if (process.argv.includes("--check")) { if (!fs.existsSync(path) || fs.readFileSync(path, "utf8") !== output) throw new Error("miniprogram build info is stale"); }
else fs.writeFileSync(path, output);
