import { resolveQWeatherVisual, type QWeatherVisualDefinition } from "@wardrobe/domain-catalog";

export type WeatherCanvasEligibility = "dynamic_today" | "static_tomorrow" | "static_unknown" | "static_fallback" | "static_stale";
export type WeatherVisualFamily = "sky" | "overcast" | "rain" | "storm" | "frozen" | "atmosphere" | "dust" | "static";

export const WEATHER_CANVAS_DRAW_ORDER = Object.freeze([
  "ambient", "air", "skyMass", "stormDepth", "volumeWeather", "blizzardContrast", "blizzardGusts",
  "rainVisibility", "rainCurtains", "visibilityLoss", "dustDensityField", "hazeStrata", "dustSignatures",
  "snowSheet", "precipitation", "blizzardForeground", "blizzardSignatures", "stormRainHighlights",
  "extremeRainGrade", "lightning", "hailEvents", "hailSignatures", "textProtection",
] as const);

export function canvasEligibility(input: { kind: "today" | "tomorrow"; code: string; forecast: boolean; stale: boolean }): WeatherCanvasEligibility {
  if (input.kind === "tomorrow") return "static_tomorrow";
  if (!input.forecast) return "static_fallback";
  if (input.stale) return "static_stale";
  if (resolveQWeatherVisual(input.code).static) return "static_unknown";
  return "dynamic_today";
}

interface SceneParams {
  visualFamily: WeatherVisualFamily; severity: number; day: boolean | null; static: boolean;
  cloudCover: number; windVector: number; visibility: number; extreme: boolean;
}
interface Particle { x: number; y: number; depth: number; phase: number; speed: number; size: number; kind: string }
interface HailParticle { x: number; y: number; depth: number; speed: number; size: number; offset: number; spin: number; bounce: number; facet: number }
interface AirLayer { seed: number; rgb: readonly [number, number, number]; density: number; speed: number; offset: number; y: number; alpha: number; scale: number }
export interface WeatherSafeRect { x: number; y: number; w: number; h: number }
export interface WeatherScene {
  code: string; key: "today" | "tomorrow"; meta: QWeatherVisualDefinition; params: SceneParams; seed: number;
  clock: number; lastDraw: number; air: AirLayer[]; precip: Particle[]; hail: HailParticle[];
  dustMotes: Particle[]; hazeMotes: Particle[]; volume: AirLayer[]; safeRects: WeatherSafeRect[];
  event: { lightningStart: number; hailStart: number; nextLightning: number; nextHail: number; phase: string };
  rng: () => number;
}

export function prototypeHash(value: unknown): number {
  let h = 2166136261;
  for (const ch of String(value)) { h ^= ch.charCodeAt(0); h = Math.imul(h, 16777619); }
  return h >>> 0;
}
export function prototypeSeeded(seed: number): () => number {
  let a = seed >>> 0;
  return () => { a = (a + 0x6D2B79F5) | 0; let t = Math.imul(a ^ a >>> 15, 1 | a); t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t; return ((t ^ t >>> 14) >>> 0) / 4294967296; };
}

function visualFamily(meta: QWeatherVisualDefinition): WeatherVisualFamily {
  if (meta.family === "clear" || meta.family === "cloud") return "sky";
  if (meta.family === "overcast") return "overcast";
  if (meta.family === "rain") return "rain";
  if (meta.family === "thunder" || meta.family === "hail") return "storm";
  if (["snow", "blizzard", "sleet", "freezing_rain"].includes(meta.family)) return "frozen";
  if (meta.family === "fog" || meta.family === "haze") return "atmosphere";
  if (meta.family === "dust") return "dust";
  return "static";
}
function paramsFor(meta: QWeatherVisualDefinition): SceneParams {
  const family = visualFamily(meta), severity = Number(meta.severity) || 0, drift = Number(meta.windDrift) || 0;
  return {
    visualFamily: family, severity, day: meta.day, static: meta.static,
    cloudCover: meta.cloud ?? (family === "sky" ? 0.15 : family === "overcast" ? 1 : ["rain", "storm", "frozen"].includes(family) ? 0.86 : 0.35),
    windVector: family === "dust" ? 0.30 + severity * 0.035 + drift * 0.075 : family === "frozen" ? 0.13 + severity * 0.035 + drift * 0.04 : family === "rain" || family === "storm" ? 0.10 + severity * 0.025 + drift * 0.06 : 0.035,
    visibility: meta.visibility ?? 1, extreme: Boolean(meta.extreme),
  };
}

export function createWeatherScene(code: string, key: "today" | "tomorrow"): WeatherScene {
  const meta = resolveQWeatherVisual(code), params = paramsFor(meta), seed = prototypeHash(`${code}:${key}:wardora-v023`), rng = prototypeSeeded(seed);
  const dark = ["overcast", "rain", "storm", "frozen"].includes(params.visualFamily);
  const nightSky = params.visualFamily === "sky" && params.day === false;
  const nightWeather = params.day === false && ["rain", "frozen"].includes(params.visualFamily);
  const rgb: readonly [number, number, number] = params.visualFamily === "storm" ? [54, 70, 82] : params.visualFamily === "dust" ? [137, 91, 52] : meta.family === "haze" ? [151, 139, 113] : nightSky ? [70, 79, 96] : nightWeather ? [66, 78, 94] : dark ? [83, 103, 113] : [164, 188, 194];
  const air: AirLayer[] = params.static ? [] : Array.from({ length: 3 }, (_, index) => ({ seed: seed + index * 977, rgb, density: Math.min(1, params.cloudCover * 0.7 + index * 0.09), speed: (0.0024 + index * 0.0018) * (params.visualFamily === "dust" ? 2.1 : meta.family === "haze" ? 0.30 : 1), offset: rng(), y: -0.12 + index * 0.12, alpha: (0.10 + index * 0.035) * (dark ? 1.35 : nightSky ? 0.82 : 1), scale: 1.18 + index * 0.18 }));
  const volume: AirLayer[] = [];
  if (!params.static && (meta.family === "blizzard" || params.visualFamily === "dust" || meta.family === "haze")) {
    const color: readonly [number, number, number] = meta.family === "blizzard" ? [235, 241, 239] : params.visualFamily === "dust" ? [154, 105, 62] : [174, 163, 137];
    for (let index = 0; index < 3; index++) volume.push({ seed: seed + 5101 + index * 619, rgb: color, density: 0.58 + index * 0.08, offset: rng(), speed: (meta.family === "blizzard" ? 0.013 : params.visualFamily === "dust" ? 0.007 : 0.0011) * (1 + index * 0.46), y: -0.24 + index * 0.18, alpha: meta.family === "blizzard" ? 0.14 + index * 0.05 : params.visualFamily === "dust" ? 0.105 + index * 0.038 : 0.065 + index * 0.028, scale: 1.55 + index * 0.28 });
  }
  let count = 0, kind = "none";
  if (params.visualFamily === "rain" || params.visualFamily === "storm") { count = 14 + Math.round(params.severity * 8 + (1 - params.visibility) * 8 + (params.extreme ? 6 : 0)); kind = "rain"; }
  if (params.visualFamily === "frozen") { count = 14 + Math.round(params.severity * 7); kind = meta.family === "freezing_rain" ? "ice" : meta.family === "sleet" ? "mix" : "snow"; }
  const precip = Array.from({ length: count }, (_, index): Particle => ({ x: rng() * 1.28 - 0.14, y: rng() * 1.22 - 0.1, depth: index % 3, phase: rng(), speed: 0.16 + rng() * 0.18, size: 0.6 + rng() * 1.25, kind: kind === "mix" ? index % 2 ? "rain" : "snow" : kind }));
  const hail = Array.from({ length: 9 }, (_, index): HailParticle => ({ x: 0.66 + rng() * 0.30, y: 0.28 + rng() * 0.22, depth: index % 3, speed: 0.78 + rng() * 0.28, size: 1 + rng() * 1.05, offset: rng() * 0.24, spin: (rng() - 0.5) * 2.1, bounce: 0.075 + rng() * 0.06, facet: rng() }));
  const dustMotes = Array.from({ length: 18 }, (_, index): Particle => ({ x: rng() * 1.18 - 0.08, y: rng(), depth: index % 3, size: 0.45 + rng() * 1.8, speed: 0.03 + rng() * 0.06, phase: rng(), kind: "dust" }));
  const hazeMotes = Array.from({ length: 12 }, (_, index): Particle => ({ x: rng(), y: rng(), depth: index % 3, size: 8 + rng() * 26, speed: 0.0005 + rng() * 0.0012, phase: rng(), kind: "haze" }));
  return { code: String(code), key, meta, params, seed, clock: 0, lastDraw: 0, air, precip, hail, dustMotes, hazeMotes, volume, safeRects: [], event: { lightningStart: -99, hailStart: -99, nextLightning: 7 + rng() * 11, nextHail: 11 + rng() * 15, phase: "安静态" }, rng };
}

export function prototypeSceneFingerprint(scene: WeatherScene, clock: number): string {
  return JSON.stringify({ code: scene.code, key: scene.key, seed: scene.seed, clock: Number(clock.toFixed(3)), family: scene.meta.family, visualFamily: scene.params.visualFamily, params: scene.params, air: scene.air, precip: scene.precip, hail: scene.hail, dustMotes: scene.dustMotes, hazeMotes: scene.hazeMotes, event: scene.event, order: WEATHER_CANVAS_DRAW_ORDER });
}

const textureCache = new Map<string, HTMLCanvasElement>();
function smooth(value: number) { return value * value * (3 - 2 * value); }
function texture(layer: AirLayer): HTMLCanvasElement {
  const key = `${layer.seed}:${layer.rgb.join(",")}:${layer.density}`;
  const found = textureCache.get(key); if (found) return found;
  const canvas = document.createElement("canvas"), width = 96, height = 56, context = canvas.getContext("2d")!;
  canvas.width = width; canvas.height = height;
  const image = context.createImageData(width, height), rng = prototypeSeeded(layer.seed);
  const grids = [24, 12, 6].map((step) => { const gridWidth = Math.ceil(width / step) + 2, gridHeight = Math.ceil(height / step) + 2; return { step, gridWidth, values: Array.from({ length: gridWidth * gridHeight }, () => rng()) }; });
  for (let y = 0; y < height; y++) for (let x = 0; x < width; x++) {
    let value = 0, total = 0;
    grids.forEach((grid, index) => { const gx = x / grid.step, gy = y / grid.step, ix = Math.floor(gx), iy = Math.floor(gy), fx = smooth(gx - ix), fy = smooth(gy - iy), a = grid.values[iy * grid.gridWidth + ix]!, b = grid.values[iy * grid.gridWidth + ix + 1]!, d = grid.values[(iy + 1) * grid.gridWidth + ix]!, e = grid.values[(iy + 1) * grid.gridWidth + ix + 1]!, top = a + (b - a) * fx, bottom = d + (e - d) * fx, weight = 1 / (1 + index * 0.7); value += (top + (bottom - top) * fy) * weight; total += weight; });
    const edge = Math.max(0, Math.min(1, (value / total - (0.42 - layer.density * 0.16)) / 0.38)), offset = (y * width + x) * 4;
    image.data[offset] = layer.rgb[0]; image.data[offset + 1] = layer.rgb[1]; image.data[offset + 2] = layer.rgb[2]; image.data[offset + 3] = Math.round(edge * 255);
  }
  context.putImageData(image, 0, 0); textureCache.set(key, canvas); return canvas;
}

const RAIN_DAY = [[[174,190,194],[212,220,218],[232,234,228]],[[156,174,181],[199,210,209],[224,228,224]],[[126,150,161],[178,193,193],[211,218,216]],[[94,121,137],[145,166,171],[184,198,199]],[[67,91,108],[112,139,150],[148,168,174]],[[45,69,88],[84,112,125],[118,141,149]],[[30,51,70],[62,89,104],[94,119,130]]] as const;
const RAIN_NIGHT = [[[30,48,67],[51,76,96],[63,89,108]],[[26,44,64],[46,71,93],[59,83,104]],[[21,39,59],[41,66,87],[53,77,98]],[[16,34,53],[34,58,79],[46,69,91]],[[12,29,47],[28,51,71],[39,61,82]],[[9,25,42],[23,45,65],[33,54,75]],[[7,21,36],[18,39,58],[28,49,69]]] as const;
const FROZEN = [[[175,194,202],[214,223,223],[230,234,230]],[[157,181,191],[202,215,216],[222,228,225]],[[139,168,182],[188,204,207],[211,220,219]],[[116,148,165],[168,189,195],[196,210,211]],[[94,126,146],[144,169,179],[177,195,200]]] as const;
type ColorScale = readonly (readonly (readonly number[])[])[];
function palette(scale: ColorScale, level: number): string[] { const clamped = Math.max(0, Math.min(scale.length - 1, level)), low = Math.floor(clamped), high = Math.min(scale.length - 1, low + 1), t = clamped - low; return scale[low]!.map((color, index) => `rgb(${color.map((value, channel) => Math.round(value + (scale[high]![index]![channel]! - value) * t)).join(",")})`); }
function precipitationPalette(scene: WeatherScene): string[] | null { const p = scene.params; if (!["rain", "storm", "frozen"].includes(p.visualFamily)) return null; const level = Math.max(0, Math.min(6, p.severity + Math.max(0, 0.7 - p.visibility) * 2 + (p.extreme ? 0.35 : 0))); if (p.day === false) return palette(RAIN_NIGHT, level); if (p.visualFamily === "frozen") return palette(FROZEN, Math.min(4, level)); return palette(RAIN_DAY, Math.min(6, level + (p.visualFamily === "storm" ? 0.35 : 0))); }
function hitsSafe(scene: WeatherScene, x1: number, y1: number, x2 = x1, y2 = y1) { const left = Math.min(x1, x2) - 2, right = Math.max(x1, x2) + 2, top = Math.min(y1, y2) - 2, bottom = Math.max(y1, y2) + 2; return scene.safeRects.some((rect) => right > rect.x && left < rect.x + rect.w && bottom > rect.y && top < rect.y + rect.h); }
function safe(scene: WeatherScene, x1: number, y1: number, x2 = x1, y2 = y1) { return hitsSafe(scene, x1, y1, x2, y2) ? 0.26 : 1; }

function ambient(context: CanvasRenderingContext2D, scene: WeatherScene, width: number, height: number) {
  const p = scene.params, night = p.day === false, precip = precipitationPalette(scene);
  const palettes: Record<WeatherVisualFamily, readonly string[]> = { sky: night ? ["#182638", "#2b3d55"] : ["#bfd5d9", "#f2dfb7"], overcast: ["#9eacb1", "#d5d9d6"], rain: precip!, storm: precip!, frozen: precip!, atmosphere: ["#b6b4a9", "#e6e1d4"], dust: ["#b48156", "#d8b78e"], static: ["#bdc5c5", "#ebe9df"] };
  const [a, b, third] = palettes[p.visualFamily], gradient = night ? context.createLinearGradient(0, 0, 0, height) : context.createLinearGradient(0, 0, width, height); gradient.addColorStop(0, a!); gradient.addColorStop(0.62, b!); gradient.addColorStop(1, third ?? (night ? "#344e64" : "#fbf2dc")); context.fillStyle = gradient; context.fillRect(0, 0, width, height);
  if (p.visualFamily === "sky" && p.day !== false) { const light = context.createRadialGradient(width * 1.02, height * 0.1, 0, width * 1.02, height * 0.1, width * 0.78); light.addColorStop(0, "rgba(224,164,62,.72)"); light.addColorStop(0.4, "rgba(241,197,118,.34)"); light.addColorStop(1, "rgba(255,255,255,0)"); context.fillStyle = light; context.fillRect(0, 0, width, height); }
}
function drawAir(context: CanvasRenderingContext2D, scene: WeatherScene, width: number, height: number, staticMode: boolean) {
  scene.air.forEach((layer) => { const travel = staticMode ? 0 : scene.clock * layer.speed, span = width * 2.35, x = -width * 0.92 + ((layer.offset + travel) % 1) * width * 0.28, y = -height * 0.34 + layer.y * height * 0.08; context.save(); context.globalAlpha = layer.alpha * (scene.code === "103" ? 0.42 : 1); context.drawImage(texture(layer), x, y, span, height * 1.72); context.restore(); });
  const p = scene.params;
  if (p.visualFamily === "overcast" || p.visualFamily === "storm") { const gradient = context.createLinearGradient(0, 0, 0, height); gradient.addColorStop(0, `rgba(35,50,61,${p.visualFamily === "storm" ? .28 : .14})`); gradient.addColorStop(.52, `rgba(102,119,127,${p.visualFamily === "storm" ? .10 : .06})`); gradient.addColorStop(1, "rgba(232,233,226,.025)"); context.fillStyle = gradient; context.fillRect(0, 0, width, height); }
}
function drawVolume(context: CanvasRenderingContext2D, scene: WeatherScene, width: number, height: number, staticMode: boolean) { scene.volume.forEach((layer, index) => { const travel = (layer.offset + (staticMode ? 0 : scene.clock) * layer.speed) % 1, span = width * (2 + index * .28), x = -width * (.95 - index * .08) + travel * width * .46, y = -height * .44 + layer.y * height * .36; context.save(); context.globalAlpha = layer.alpha; if (scene.meta.family === "blizzard") context.transform(1, -.015, Math.max(.12, scene.params.windVector) * .38, 1, -width * .12, 0); context.drawImage(texture(layer), x, y, span, height * 1.85); context.restore(); }); if(scene.meta.family==="blizzard"){const loss=1-scene.params.visibility,g=context.createLinearGradient(0,0,width,height);g.addColorStop(0,`rgba(62,86,101,${.12+loss*.18})`);g.addColorStop(.46,`rgba(196,211,213,${.11+loss*.24})`);g.addColorStop(1,`rgba(239,241,235,${.18+loss*.38})`);context.fillStyle=g;context.fillRect(0,0,width,height)} }
function overlayGradient(context: CanvasRenderingContext2D, width: number, height: number, stops: readonly [number, string][]) { const gradient = context.createLinearGradient(0, 0, width, height); stops.forEach(([offset, color]) => gradient.addColorStop(offset, color)); context.fillStyle = gradient; context.fillRect(0, 0, width, height); }
function drawStormDepth(context: CanvasRenderingContext2D, scene: WeatherScene, width: number, height: number) { if(scene.params.visualFamily!=="storm")return;const top=context.createRadialGradient(width*.72,-height*.08,0,width*.72,-height*.08,width*.82);top.addColorStop(0,"rgba(24,39,51,.34)");top.addColorStop(.42,"rgba(46,64,76,.24)");top.addColorStop(1,"rgba(91,111,119,0)");context.fillStyle=top;context.fillRect(0,0,width,height);const shelf=context.createRadialGradient(width*.16,height*.03,0,width*.16,height*.03,width*.66);shelf.addColorStop(0,"rgba(48,65,76,.22)");shelf.addColorStop(.56,"rgba(70,88,98,.12)");shelf.addColorStop(1,"rgba(95,113,120,0)");context.fillStyle=shelf;context.fillRect(0,0,width,height*.72);const cold=context.createLinearGradient(0,height*.34,width,height);cold.addColorStop(0,"rgba(124,144,151,.02)");cold.addColorStop(.58,"rgba(177,193,193,.08)");cold.addColorStop(1,"rgba(218,224,217,.16)");context.fillStyle=cold;context.fillRect(0,height*.22,width,height*.78); }
function drawRainVisibility(context: CanvasRenderingContext2D, scene: WeatherScene, width: number, height: number) { const p=scene.params;if(p.visualFamily!=="rain"||p.visibility>=1)return;const loss=1-p.visibility,extreme=p.extreme||p.visibility<=.25;overlayGradient(context,width,height,[[0,`rgba(32,51,65,${loss*(extreme?.22:.12)})`],[.52,`rgba(104,126,134,${loss*(extreme?.26:.16)})`],[1,`rgba(185,201,202,${loss*(extreme?.30:.19)})`]]); }
function drawRainCurtains(context: CanvasRenderingContext2D, scene: WeatherScene, width: number, height: number, staticMode: boolean) { const p=scene.params;if(!["rain","storm"].includes(p.visualFamily)||p.severity<2.5)return;const strength=Math.min(1,(p.severity-2.2)/1.8),rank=scene.code==="312"?3:scene.code==="308"?2:scene.code==="311"?1:0,extreme=rank>1||p.extreme||p.visibility<=.25,time=staticMode?0:scene.clock,base=context.createLinearGradient(0,0,width,height);base.addColorStop(0,`rgba(24,43,58,${(.04+rank*.018)*strength})`);base.addColorStop(.48,`rgba(91,116,128,${(.06+(1-p.visibility)*.05+rank*.018)*strength})`);base.addColorStop(1,`rgba(181,201,204,${(.075+(1-p.visibility)*.065+rank*.018)*strength})`);context.fillStyle=base;context.fillRect(0,0,width,height);const layers=2+rank;for(let index=0;index<layers;index++){const travel=(time*(.034+index*.011+rank*.006)+index*.37)%1.75,x=(-.58+travel)*width,band=width*(.18+index*.045+rank*.018),gradient=context.createLinearGradient(x,0,x+band,0),alpha=(.024+index*.012+rank*.014)*strength;gradient.addColorStop(0,"rgba(235,244,245,0)");gradient.addColorStop(.34,`rgba(217,233,237,${alpha*.58})`);gradient.addColorStop(.62,`rgba(240,247,247,${alpha})`);gradient.addColorStop(1,"rgba(235,244,245,0)");context.save();context.transform(1,0,-(p.windVector*.48+rank*.035),1,0,0);context.fillStyle=gradient;context.fillRect(x,-height*.16,band,height*1.36);context.restore()}if(extreme&&rank>=2)overlayGradient(context,width,height,[[0,"rgba(27,46,59,.02)"],[.58,`rgba(116,141,150,${.08+rank*.035})`],[1,`rgba(202,216,216,${.15+rank*.045})`]]); }
function drawVisibility(context: CanvasRenderingContext2D, scene: WeatherScene, width: number, height: number) { const p = scene.params; if (p.visibility >= 1 || p.visualFamily === "rain") return; const loss = 1 - p.visibility; if (p.visualFamily === "dust") overlayGradient(context, width, height, [[0,`rgba(92,57,35,${loss*.15})`],[.55,`rgba(158,107,65,${loss*.25})`],[1,`rgba(205,154,96,${loss*.36})`]]); else if (scene.meta.family === "haze") overlayGradient(context, width, height, [[0,`rgba(117,111,96,${loss*.14})`],[.5,`rgba(169,158,133,${loss*.24})`],[1,`rgba(214,205,181,${loss*.31})`]]); else overlayGradient(context, width, height, [[0,`rgba(190,207,210,${loss*.10})`],[.52,`rgba(217,227,226,${loss*.22})`],[1,`rgba(236,239,233,${loss*.34})`]]); }
function drawHaze(context: CanvasRenderingContext2D, scene: WeatherScene, width: number, height: number, staticMode: boolean) { if (scene.code !== "512") return; const time = staticMode ? 0 : scene.clock, layers = [{speed:.0042,width:.56,alpha:.16,tint:"178,163,129",offset:.08},{speed:.0027,width:.72,alpha:.13,tint:"117,112,98",offset:.44},{speed:.0015,width:.88,alpha:.11,tint:"214,197,158",offset:.76}]; context.save(); layers.forEach((layer) => { const center = ((layer.offset + time * layer.speed) % 1.62 - .26) * width, band = width * layer.width, gradient = context.createLinearGradient(center - band, 0, center + band, 0); gradient.addColorStop(0,`rgba(${layer.tint},0)`); gradient.addColorStop(.35,`rgba(${layer.tint},${layer.alpha*.62})`); gradient.addColorStop(.58,`rgba(${layer.tint},${layer.alpha})`); gradient.addColorStop(1,`rgba(${layer.tint},0)`); context.fillStyle=gradient; context.beginPath(); context.moveTo(center-band,-height*.1); context.bezierCurveTo(center-band*.78,height*.26,center-band*.9,height*.58,center-band*.7,height*1.1); context.lineTo(center+band,height*1.1); context.bezierCurveTo(center+band*.84,height*.7,center+band*.92,height*.3,center+band*.78,-height*.1); context.closePath(); context.fill(); }); context.restore(); }
function drawDust(context: CanvasRenderingContext2D, scene: WeatherScene, width: number, height: number, staticMode: boolean) {
  if (scene.code !== "508") return;
  const time = staticMode ? 0 : scene.clock;
  context.save(); context.globalCompositeOperation="saturation"; context.fillStyle="rgba(109,105,98,.34)"; context.fillRect(0,0,width,height); context.globalCompositeOperation="source-over"; context.fillStyle="rgba(72,61,52,.055)"; context.fillRect(0,0,width,height);
  const layers=[[.17,.24,1.10,.78,.20,.070,"64,60,56",.34],[.72,.46,1.28,.84,2.55,.055,"126,94,70",.30],[.43,.76,1.16,.70,4.70,.063,"84,77,69",.27]] as const;
  layers.forEach(([cx,cy,rx,ry,phase,speed,color,alpha])=>{const drift=Math.sin(time*speed+phase),lift=Math.sin(time*speed*.61+phase*1.37);context.save();context.translate(width*(cx+drift*.18),height*(cy+lift*.07));context.scale(rx,ry);const radius=width*.52,g=context.createRadialGradient(0,0,0,0,0,radius);g.addColorStop(0,`rgba(${color},${alpha})`);g.addColorStop(.34,`rgba(${color},${alpha*.72})`);g.addColorStop(.68,`rgba(${color},${alpha*.24})`);g.addColorStop(1,`rgba(${color},0)`);context.fillStyle=g;context.fillRect(-radius,-radius,radius*2,radius*2);context.restore()});
  const plume=[{color:"44,44,42",alpha:.36,phase:.3,nodes:[[.02,.18,.34,.72],[.31,.36,.44,.61],[.66,.25,.31,.78],[.94,.43,.28,.64]]},{color:"156,124,92",alpha:.22,phase:2.75,nodes:[[.08,.72,.27,.68],[.39,.55,.38,.58],[.69,.74,.32,.76],[1.01,.54,.25,.62]]}];
  plume.forEach((layer)=>layer.nodes.forEach(([bx,by,size,aspect],index)=>{const phase=layer.phase+index*.83,x=width*(bx+Math.sin(time*.05+phase)*.105),y=height*(by+Math.sin(time*.0355+phase*1.19)*.052);context.save();context.translate(x,y);context.scale(1,aspect);const radius=width*size,g=context.createRadialGradient(0,0,0,0,0,radius);g.addColorStop(0,`rgba(${layer.color},${layer.alpha})`);g.addColorStop(.28,`rgba(${layer.color},${layer.alpha*.82})`);g.addColorStop(.64,`rgba(${layer.color},${layer.alpha*.3})`);g.addColorStop(1,`rgba(${layer.color},0)`);context.fillStyle=g;context.fillRect(-radius,-radius,radius*2,radius*2);context.restore()}));
  const ground=[[.04,1.07,1.08,.82,.25,.055,"61,55,50",.39],[.54,1.01,1.24,.72,2.4,.044,"88,70,58",.34],[1.01,1.1,1.05,.88,4.85,.05,"119,87,64",.28]] as const;
  ground.forEach(([cx,cy,rx,ry,phase,speed,color,alpha])=>{context.save();context.translate(width*(cx+Math.sin(time*speed+phase)*.14),height*(cy+Math.sin(time*speed*.73+phase*1.22)*.035));context.scale(rx,ry);const radius=width*.54,g=context.createRadialGradient(0,0,0,0,0,radius);g.addColorStop(0,`rgba(${color},${alpha})`);g.addColorStop(.38,`rgba(${color},${alpha*.76})`);g.addColorStop(.73,`rgba(${color},${alpha*.27})`);g.addColorStop(1,`rgba(${color},0)`);context.fillStyle=g;context.fillRect(-radius,-radius,radius*2,radius*2);context.restore()});
  context.restore();
}

function drawPrecipitation(context: CanvasRenderingContext2D, scene: WeatherScene, width: number, height: number, staticMode: boolean) { const p = scene.params, time = staticMode ? 0 : scene.clock; for (const particle of scene.precip) { const depth=(particle.depth+1)/3,speed=(particle.kind==="rain"||particle.kind==="ice")?1.45+p.severity*.22+(1-p.visibility)*.5+(p.extreme?.25:0):1,y=((particle.y+time*particle.speed*speed*(.58+depth*.84))%1.24-.09)*height,baseX=((particle.x+time*p.windVector*particle.speed*speed)%1.26-.1)*width,x=baseX+(particle.kind==="snow"?Math.sin(time*(.75+depth*.32)+particle.phase*6.283)*(1+depth*2.1):0); if (particle.kind === "rain" || particle.kind === "ice") { const length=(5.2+p.severity*1.9+(1-p.visibility)*3.2)*(.48+depth*.78),dx=length*p.windVector*(1.2+depth*.5),factor=safe(scene,x,y,x+dx,y+length),alpha=(particle.kind==="ice"?.16+depth*.14:.075+depth*.13)*factor; context.lineCap="round"; context.strokeStyle=particle.kind==="ice"?`rgba(220,234,239,${alpha})`:`rgba(84,110,123,${alpha})`; context.lineWidth=.28+depth*.54; context.beginPath();context.moveTo(x,y);context.lineTo(x+dx,y+length);context.stroke(); } else if (particle.kind === "snow") { const blizzard=scene.meta.family==="blizzard",factor=safe(scene,x,y,x+10,y-2); if(blizzard){const turbulence=Math.sin(time*.68+particle.phase*6.28)*(1.1+depth*2.2),length=2.8+depth*5.8+particle.size*1.4,thick=.55+depth*1.35;context.save();context.translate(x,y+turbulence);context.rotate(-.10+(particle.phase-.5)*.20);context.fillStyle=`rgba(244,249,248,${(.14+depth*.34)*factor})`;context.beginPath();context.ellipse(0,0,length,thick,-.12,0,Math.PI*2);context.fill();context.restore()}else{const radius=.72+depth*.82+particle.size*.30;context.fillStyle=`rgba(250,252,250,${Math.min(.84,.33+depth*.4)})`;context.beginPath();context.ellipse(x,y,radius,radius*.62,particle.phase*Math.PI,0,Math.PI*2);context.fill()}} } context.lineCap="butt"; }
function tapered(context: CanvasRenderingContext2D,x:number,y:number,dx:number,dy:number,width:number,color:string){const length=Math.hypot(dx,dy)||1,nx=-dy/length*width,ny=dx/length*width,mx=x+dx*.56,my=y+dy*.56;context.fillStyle=color;context.beginPath();context.moveTo(x,y);context.lineTo(mx+nx,my+ny);context.lineTo(x+dx,y+dy);context.lineTo(mx-nx,my-ny);context.closePath();context.fill()}
function drawStormHighlights(context: CanvasRenderingContext2D,scene:WeatherScene,width:number,height:number,staticMode:boolean){const p=scene.params,storm=p.visualFamily==="storm",heavy=p.visualFamily==="rain"&&p.severity>=3&&p.visibility<=.5;if(!storm&&!heavy)return;const time=staticMode?0:scene.clock,extreme=p.extreme||p.visibility<=.25,stride=storm?2:extreme?2:3,speed=2.05+p.severity*.24+(1-p.visibility)*.55;for(let index=0;index<scene.precip.length;index+=stride){const particle=scene.precip[index]!,depth=(particle.depth+1)/3,y=((particle.y+time*particle.speed*speed*(.66+depth*.94))%1.24-.09)*height,x=((particle.x+time*p.windVector*particle.speed*speed)%1.26-.1)*width,length=(9+p.severity*2.4+(1-p.visibility)*3.4)*(.62+depth*.74),dx=length*p.windVector*1.8,factor=safe(scene,x,y,x+dx,y+length),focus=storm?(x>width*.56||y>height*.72?1:.56):1,alpha=((storm?.34:.18)+depth*(storm?.24:.20)+(extreme?.10:0))*focus;tapered(context,x,y,dx,length,.26+depth*.38+(extreme?.08:0),`rgba(245,250,250,${alpha*factor})`)}}
function drawBlizzardGusts(context:CanvasRenderingContext2D,width:number,height:number){context.save();context.globalCompositeOperation="screen";for(const gust of [{x:.18*width,y:.34*height,r:.78*width,a:.19},{x:.84*width,y:.70*height,r:.92*width,a:.16}]){const gradient=context.createRadialGradient(gust.x,gust.y,0,gust.x,gust.y,gust.r);gradient.addColorStop(0,`rgba(247,250,248,${gust.a})`);gradient.addColorStop(.30,`rgba(232,240,240,${gust.a*.78})`);gradient.addColorStop(.62,`rgba(218,232,234,${gust.a*.34})`);gradient.addColorStop(1,"rgba(208,225,230,0)");context.fillStyle=gradient;context.fillRect(0,0,width,height)}context.restore()}
function drawSnowSheet(context:CanvasRenderingContext2D,scene:WeatherScene,width:number,height:number,staticMode:boolean){if(scene.meta.family!=="blizzard")return;const time=staticMode?0:scene.clock,gusts=[{x:(.30+time*.007)*width,y:.28*height,r:.72*width,a:.13},{x:(.78+time*.011)*width,y:.72*height,r:.86*width,a:.16}];context.save();context.transform(1,-.025,.16,1,-width*.06,0);for(const gust of gusts){const gradient=context.createRadialGradient(gust.x,gust.y,0,gust.x,gust.y,gust.r);gradient.addColorStop(0,`rgba(247,250,248,${gust.a})`);gradient.addColorStop(.38,`rgba(232,240,239,${gust.a*.66})`);gradient.addColorStop(.72,`rgba(218,231,233,${gust.a*.22})`);gradient.addColorStop(1,"rgba(210,227,231,0)");context.fillStyle=gradient;context.fillRect(-width*.18,-height*.18,width*1.36,height*1.36)}context.restore()}
function drawBlizzardSignatures(context:CanvasRenderingContext2D,scene:WeatherScene,width:number,height:number,staticMode:boolean){if(scene.meta.family!=="blizzard")return;const time=staticMode?0:scene.clock,spots=[[.16,.22,2.2,.9],[.74,.16,3,1.2],[.88,.44,3.8,1],[.62,.68,2.8,1.3],[.92,.82,4.1,1.1],[.38,.86,2.5,.8]];spots.forEach(([bx,by,rw,ratio],index)=>{const x=((bx!+time*(.014+index*.0015))%1.12)*width,y=(by!+Math.sin(time*.26+index*1.3)*.018)*height,rh=rw!*.34*ratio!,factor=Math.max(.6,safe(scene,x-rw!,y-rh,x+rw!,y+rh));context.save();context.translate(x,y);context.rotate(-.24+(index%3)*.13);context.fillStyle=`rgba(248,251,249,${(.34+index*.035)*factor})`;context.beginPath();context.ellipse(0,0,rw!,rh,-.14,0,Math.PI*2);context.fill();context.restore()})}
function lightningPhase(scene: WeatherScene) { const delta=scene.clock-scene.event.lightningStart;if(delta<0)return{phase:"安静态",cloud:0,mist:0,rain:0};if(delta<.07){const t=1-delta/.07;return{phase:"首次云内受光",cloud:.72*t+.15,mist:.05,rain:.04}}if(delta<.15){const t=1-(delta-.07)/.08;return{phase:"首次雨幕响应",cloud:.22*t+.05,mist:.14*t+.04,rain:.42*t+.08}}if(delta<.27){const t=1-(delta-.15)/.12;return{phase:"近地雾回暗",cloud:.03*t,mist:.16*t*t,rain:.05*t}}if(delta<.36){const t=1-(delta-.27)/.09;return{phase:"第二次云内受光",cloud:.84*t+.13,mist:.08,rain:.07}}if(delta<.48){const t=1-(delta-.36)/.12;return{phase:"第二次雨幕响应",cloud:.24*t+.04,mist:.20*t+.04,rain:.52*t+.08}}if(delta<1.18){const t=1-(delta-.48)/.70;return{phase:"分层回暗",cloud:.12*t,mist:.19*t*t,rain:.09*t}}return{phase:"安静态",cloud:0,mist:0,rain:0}; }
function updateEvents(scene: WeatherScene, dynamic: boolean) { if(!dynamic||scene.key!=="today"||scene.params.static)return;const phase=lightningPhase(scene);if(scene.params.visualFamily==="storm"&&scene.clock>=scene.event.nextLightning&&phase.phase==="安静态"){scene.event.lightningStart=scene.clock;scene.event.nextLightning=scene.clock+7+scene.rng()*11}const hailActive=scene.clock-scene.event.hailStart<1.48;if(scene.meta.family==="hail"&&scene.clock>=scene.event.nextHail&&!hailActive&&lightningPhase(scene).phase==="安静态"){scene.event.hailStart=scene.clock;scene.event.nextHail=scene.clock+12+scene.rng()*15} }
function drawLightning(context: CanvasRenderingContext2D, scene: WeatherScene, width: number, height: number) { const phase=lightningPhase(scene);scene.event.phase=phase.phase;if(!phase.cloud)return;const cloud=context.createRadialGradient(width*.80,height*.10,width*.02,width*.80,height*.10,width*.72);cloud.addColorStop(0,`rgba(249,252,253,${phase.cloud*.90})`);cloud.addColorStop(.24,`rgba(225,239,244,${phase.cloud*.64})`);cloud.addColorStop(.58,`rgba(185,208,219,${phase.cloud*.25})`);cloud.addColorStop(1,"rgba(148,177,192,0)");context.fillStyle=cloud;context.fillRect(0,0,width,height); }
function drawHail(context: CanvasRenderingContext2D, scene: WeatherScene, width: number, height: number, staticMode: boolean) { if(staticMode||scene.key!=="today"||scene.meta.family!=="hail")return;const delta=scene.clock-scene.event.hailStart;if(delta<0||delta>=1.48)return;const chunks=[[.68,.34,.00,4.6],[.82,.29,.08,5.5],[.93,.39,.16,4.2],[.76,.46,.23,5.0]] as const;chunks.forEach(([bx,by,offset,size],index)=>{const local=delta-offset;if(local<=0)return;const ground=.82+index*.015,radius=size*(1+index*.04);let x=(bx+Math.min(local,1.2)*.055)*width,y=by*height,fade=1;if(local<.66)y=(by+smooth(local/.66)*(ground-by))*height;else if(local<1.08){const bounce=(local-.66)/.42;y=(ground-Math.sin(bounce*Math.PI)*(.085-index*.008)*(1-bounce*.34))*height;x+=bounce*width*.026}else{fade=Math.max(0,1-(local-1.08)/.4);y=ground*height}context.save();context.translate(x,y);context.rotate(-.55+index*.63+local*2.2);context.fillStyle=`rgba(145,190,210,${.90*fade})`;context.beginPath();context.moveTo(-radius*.92,-radius*.22);context.lineTo(-radius*.2,-radius);context.lineTo(radius*.88,-radius*.44);context.lineTo(radius*.68,radius*.56);context.lineTo(-radius*.36,radius*.86);context.closePath();context.fill();context.restore()}); }
function drawTextProtection(context: CanvasRenderingContext2D, scene: WeatherScene, width: number, height: number) { const p=scene.params;if(!(p.severity>=3||p.visibility<.55||p.visualFamily==="storm")||!scene.safeRects.length)return;const color=p.visualFamily==="dust"?"226,208,177":"221,230,229",alpha=p.visualFamily==="dust"?.15:scene.meta.family==="blizzard"?.19:.16,field=context.createRadialGradient(width*.38,height*.52,0,width*.38,height*.52,width*.88);field.addColorStop(0,`rgba(${color},${alpha})`);field.addColorStop(.48,`rgba(${color},${alpha*.62})`);field.addColorStop(1,`rgba(${color},0)`);context.fillStyle=field;context.fillRect(0,0,width,height);const top=context.createRadialGradient(width*.88,height*.12,0,width*.88,height*.12,width*.38);top.addColorStop(0,`rgba(${color},${alpha*.56})`);top.addColorStop(1,`rgba(${color},0)`);context.fillStyle=top;context.fillRect(0,0,width,height); }

export function renderWeatherScene(context: CanvasRenderingContext2D, scene: WeatherScene, width: number, height: number, timeMs: number, dynamic: boolean, staticMode = false) {
  const delta = dynamic ? Math.min(.075, Math.max(0, (timeMs - scene.lastDraw) / 1000 || 0)) : 0; scene.lastDraw = timeMs; if (dynamic) scene.clock += delta; updateEvents(scene, dynamic);
  context.clearRect(0,0,width,height);
  ambient(context,scene,width,height); drawAir(context,scene,width,height,staticMode||scene.params.static); drawStormDepth(context,scene,width,height); drawVolume(context,scene,width,height,staticMode||scene.params.static);
  if(scene.meta.family==="blizzard"){overlayGradient(context,width,height,[[0,"rgba(30,53,70,.52)"],[.38,"rgba(66,92,106,.35)"],[.68,"rgba(160,184,190,.17)"],[1,"rgba(241,243,237,.30)"]]);drawBlizzardGusts(context,width,height)}
  drawRainVisibility(context,scene,width,height); drawRainCurtains(context,scene,width,height,staticMode); drawVisibility(context,scene,width,height); drawDust(context,scene,width,height,staticMode); drawHaze(context,scene,width,height,staticMode); drawSnowSheet(context,scene,width,height,staticMode); drawPrecipitation(context,scene,width,height,staticMode); drawBlizzardSignatures(context,scene,width,height,staticMode); drawStormHighlights(context,scene,width,height,staticMode);
  drawLightning(context,scene,width,height); drawHail(context,scene,width,height,staticMode); drawTextProtection(context,scene,width,height);
}

export function triggerWeatherSceneEvent(scene: WeatherScene, kind: "lightning" | "hail") { if(scene.params.static||scene.key!=="today"||scene.params.visualFamily!=="storm")return false;if(kind==="lightning"){scene.event.lightningStart=scene.clock;scene.event.nextLightning=scene.clock+9+scene.rng()*9;return true}if(scene.meta.family==="hail"){scene.event.hailStart=scene.clock;scene.event.nextHail=scene.clock+14+scene.rng()*12;return true}return false; }
